services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  web:
    image: ghcr.io/gxjakkap/yookbeer-web:main
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.guestbook.rule=Host(`yb.guntxjakka.me`)"
      - "com.centurylinklabs.watchtower.enable=true"
    env_file: ".env"
    deploy:
      mode: replicated
      replicas: 2
    restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    user: postgres
    env_file: ".env"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_LOG_STATEMENT=all
      - POSTGRES_LOG_CONNECTIONS=true
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data: