services:
    web:
        image: ghcr.io/gxjakkap/yookbeer-web:main
        env_file: ".env"
        restart: always
        networks:
            - yookbeer

    db:
        image: postgres
        restart: always
        user: postgres
        env_file: ".env"
        networks:
            - yookbeer
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_LOG_STATEMENT=all
            - POSTGRES_LOG_CONNECTIONS=true
        ports:
            - "5432:5432"
volumes:
    db-data:

networks:
    yookbeer:
        driver: bridge
