services:
    web:
        image: ghcr.io/gxjakkap/yookbeer-web:main
        pull_policy: always
        env_file: ".env"
        restart: always
        networks:
            - yookbeer

    db:
        image: postgres
        restart: always
        user: postgres
        env_file: ".env"
        networks:
            - yookbeer
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_LOG_STATEMENT=all
            - POSTGRES_LOG_CONNECTIONS=true
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d yookbeer"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s
volumes:
    db-data:

networks:
    yookbeer:
        driver: bridge
