services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  web:
    image: ghcr.io/gxjakkap/yookbeer-web:latest
    ports: 
      - "8080:8080"
    env_file: ".env"
    deploy:
      mode: replicated
      replicas: 2
    restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    user: postgres
    env_file: ".env"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_LOG_STATEMENT=all
      - POSTGRES_LOG_CONNECTIONS=true
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data: