import type { Metadata } from "next"

import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {(process.env.NODE_ENV === "development" && process.env.YB_ENABLE_REACT_SCAN === '1') && (
        <head>
          <script src="https://unpkg.com/react-scan/dist/auto.global.js" async />
        </head>
      )}
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
